packages:
  - 'docs'
  - 'packages/*'
  - 'samples/*'
  - '!samples/teamspace-nextjs'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - nx
  - sharp

catalog:
  '@eslint/js': '9.25.0'
  '@types/react': '19.2.14'
  '@types/react-dom': '19.2.3'
  '@wso2/eslint-plugin': 'git+https://github.com/brionmario/wso2-ui-configs.git#d3041825a4f8f235c8f9fa36b55cf29d54e791c8&path:packages/eslint-plugin'
  '@wso2/prettier-config': 'git+https://github.com/brionmario/wso2-ui-configs.git#d3041825a4f8f235c8f9fa36b55cf29d54e791c8&path:packages/prettier-config'
  '@wso2/stylelint-config': 'git+https://github.com/brionmario/wso2-ui-configs.git#d3041825a4f8f235c8f9fa36b55cf29d54e791c8&path:packages/stylelint-config'
  dompurify: '3.3.1'
  react: '19.2.4'
  react-dom: '19.2.4'
overrides:
  pbkdf2: 3.1.3
  sha.js: 2.4.12
  nx>axios: 1.13.5
  '@asgardeo/auth-spa>axios': 1.13.5
  test-exclude>glob: 10.5.0
  js-beautify>glob: 10.5.0
  '@types/react': 19.1.5
  '@types/react-dom': 19.1.5
  js-yaml: 4.1.1
  read-yaml-file: 2.1.0
  '@isaacs/brace-expansion': 5.0.1
  '@eslint/plugin-kit': 0.3.4
  tmp: 0.2.4
  min-document: 2.19.1
  lodash: 4.17.23
  tar: 7.5.8
  seroval: 1.4.1
  qs: 6.14.1
  '@vitejs/plugin-vue>vite': 7.1.12
  prettier: 2.6.2
  '@wso2/eslint-plugin>@typescript-eslint/eslint-plugin': 6.21.0
  '@wso2/eslint-plugin>@typescript-eslint/parser': 6.21.0
  '@wso2/eslint-plugin>@typescript-eslint/type-utils': 6.21.0
  '@wso2/eslint-plugin>@typescript-eslint/utils': 6.21.0
auditConfig:
  ignoreGhsas:
    - CVE-2026-26996
strictPeerDependencies: false
autoInstallPeers: true
