packages:
  - 'docs'
  - 'packages/*'
  - 'samples/*'
  - '!samples/teamspace-nextjs'

allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  core-js: true
  esbuild: true
  nx: true
  sharp: true
  unrs-resolver: true

auditConfig:
  ignoreGhsas:
    - CVE-2026-26996

autoInstallPeers: true
strictPeerDependencies: false

catalog:
  '@eslint/js': '9.25.0'
  '@types/react': '19.2.14'
  '@types/react-dom': '19.2.3'
  '@wso2/eslint-plugin': 'git+https://github.com/brionmario/wso2-ui-configs.git#d3041825a4f8f235c8f9fa36b55cf29d54e791c8&path:packages/eslint-plugin'
  '@wso2/prettier-config': 'git+https://github.com/brionmario/wso2-ui-configs.git#d3041825a4f8f235c8f9fa36b55cf29d54e791c8&path:packages/prettier-config'
  '@wso2/stylelint-config': 'git+https://github.com/brionmario/wso2-ui-configs.git#d3041825a4f8f235c8f9fa36b55cf29d54e791c8&path:packages/stylelint-config'
  dompurify: '3.3.1'
  react: '19.2.4'
  react-dom: '19.2.4'

overrides:
  '@asgardeo/auth-spa>axios': 1.13.5
  '@eslint/plugin-kit': 0.3.4
  '@isaacs/brace-expansion': 5.0.1
  '@types/react': 19.1.5
  '@types/react-dom': 19.1.5
  '@vitejs/plugin-vue>vite': 7.1.12
  '@wso2/eslint-plugin>@typescript-eslint/eslint-plugin': 6.21.0
  '@wso2/eslint-plugin>@typescript-eslint/parser': 6.21.0
  '@wso2/eslint-plugin>@typescript-eslint/type-utils': 6.21.0
  '@wso2/eslint-plugin>@typescript-eslint/utils': 6.21.0
  js-beautify>glob: 10.5.0
  js-yaml: 4.1.1
  lodash: 4.17.23
  min-document: 2.19.1
  nx>axios: 1.13.5
  pbkdf2: 3.1.3
  prettier: 2.6.2
  qs: 6.14.1
  read-yaml-file: 2.1.0
  seroval: 1.4.1
  sha.js: 2.4.12
  tar: 7.5.8
  test-exclude>glob: 10.5.0
  tmp: 0.2.4
